# Generated by Django 4.2.1 on 2023-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pincode1',
            field=models.CharField(max_length=6, null=True, verbose_name='Пин-код1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
