# Generated by Django 4.2.1 on 2023-05-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_pincode1_alter_student_is_visited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='pincode1',
            new_name='logout_pincode',
        ),
    ]
