# Generated by Django 4.2.1 on 2023-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_pincode1_student_logout_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_exit',
            field=models.BooleanField(default=False),
        ),
    ]
